### ISSUE TITLE
Space in 'accessibility ' link

### ISSUE THREAD

**Issue by adyhoran1** [DFE-Digital/apply-the-service-standard-in-dfe#21]
There's this bullet point in the [Make the service simple to use](https://apply-the-service-standard.education.gov.uk/service-standard/4-make-the-service-simple-to-use) page:

- how the service meets [accessibility ](https://design.education.gov.uk/accessibility/)requirements

There's an extra space in the 'accessibility ' link text - could this be removed?

I understand the spreadsheet, version date and homepage may need updating in-line with this.

**Comment by kerryalyons** [comment]
Space deleted. No change to link. Link worked.

Spreadsheet - links generally need reviewing and checking - will review with @andyjones81

**Comment by adyhoran1** [comment]
Thanks @kerryalyons 🙂

**Comment by kerryalyons** [comment]
merged onto main branch.
